services:
  nginx:
    container_name: nginx
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    expose:
      - "9000"
    
  redis:
    container_name: redis
    restart: always
    volumes:
      - redis:/data
    networks:
      - inception
    build: 
      context: ./requirements/bonus/redis
    env_file:
      - .env
    depends_on:
      - wordpress
    expose:
      - "6379"

  ftp:
    container_name: ftp
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: ./requirements/bonus/ftp
    env_file:
      - .env
    depends_on:
      - wordpress
    expose:
      - "21"

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/m3ayz00/data/mariadb
      o: bind
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/m3ayz00/data/wordpress
      o: bind
  redis:
    name: redis
    driver: local
    driver_opts:
      type: none
      device: /home/m3ayz00/data/redis
      o: bind