services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    build: 
      context: ./requirements/wordpress
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - mariadb
    expose:
      - "9000"
    
  redis:
    container_name: redis
    build: 
      context: ./requirements/bonus/redis
    restart: always
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - wordpress
    expose:
      - "6379"

  ftp:
    container_name: ftp
    build: 
      context: ./requirements/bonus/ftp
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - wordpress
    expose:
      - "21"
      - "50000-51000"
    
  adminer:
    container_name: adminer
    build: 
      context: ./requirements/bonus/adminer
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env
    expose:
      - "8080"

  my-website:
    container_name: my-website
    build: 
      context: ./requirements/bonus/my-website
    networks:
      - inception
    expose:
      - "80"
    env_file:
      - .env

  portainer:
    container_name: portainer
    build: 
      context: ./requirements/bonus/portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      - inception
    env_file:
      - .env
    expose:
      - "9001"

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/m3ayz00/data/mariadb
      o: bind
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/m3ayz00/data/wordpress
      o: bind
  portainer:
    name: portainer
    driver: local
    driver_opts:
      type: none
      device: /home/m3ayz00/data/portainer
      o: bind