services:
  nginx:
    container_name: nginx
    restart: always
    volumes:
      - /home/m3ayz00/data/wordpress:/var/www/wordpress
    networks:
      - inception
    build:
      context: ./requirements/nginx
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    restart: always
    volumes:
      - /home/m3ayz00/data/mariadb:/var/lib/mysql
    networks:
      - inception
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    restart: always
    volumes:
      - /home/m3ayz00/data/wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    expose:
      - "9000"
    
  redis:
    container_name: redis
    restart: always
    networks:
      - inception
    build: 
      context: ./requirements/bonus/redis
    env_file:
      - .env
    depends_on:
      - wordpress
    expose:
      - "6379"

networks:
  inception:
    driver: bridge